package com.module.autographs.usedcarsales.microservice.util;

public class Constants {

    // HTTP STATUS CODES
    public static final String HTTP_RESPONSE_CODE_OK = "200";
    public static final String HTTP_RESPONSE_CODE_INTERNAL_SERVER_ERROR = "500";

    // ALL API PATHS

    // 1 - USED CAR SALES
    public static final String USED_CARS_SALES_GET_API_PATH = "/getAllUsedCarSalesData";
    public static final String USED_CARS_SALES_POST_API_PATH = "/addUsedCarSalesData";
    public static final String USED_CARS_SALES_DELETE_ALL_API_PATH = "/deleteAllUsedCarSalesData";

    // 2 - USED CAR SALES TOP COLORS
    public static final String USED_CARS_TOP_COLORS_SALES_GET_API_PATH = "/getAllUsedCarSalesTopColorsData";
    public static final String USED_CARS_TOP_COLORS_SALES_POST_API_PATH = "/addUsedCarSalesTopColorsData";
    public static final String USED_CARS_TOP_COLORS_SALES_DELETE_ALL_API_PATH = "/deleteAllUsedCarSalesTopColorsData";

    // 3 - USED CAR SALES TOP MODELS
    public static final String USED_CARS_TOP_MODELS_SALES_GET_API_PATH = "/getAllUsedCarSalesTopModelsData";
    public static final String USED_CARS_TOP_MODELS_SALES_POST_API_PATH = "/addUsedCarSalesTopModelsData";
    public static final String USED_CARS_TOP_MODELS_SALES_DELETE_ALL_API_PATH = "/deleteAllUsedCarSalesTopModelData";

    // 4 - USED CAR SALES TOP REGIONS
    public static final String USED_CARS_TOP_REGIONS_SALES_GET_API_PATH = "/getAllUsedCarSalesTopRegionsData";
    public static final String USED_CARS_TOP_REGIONS_SALES_POST_API_PATH = "/addUsedCarSalesTopRegionsData";
    public static final String USED_CARS_TOP_REGIONS_SALES_DELETE_ALL_API_PATH = "/deleteAllUsedCarSalesTopRegionsData";


    // ALL SWAGGER CONSTANTS BELOW ---------------------------------------------------------------------------------------------------------

    // 1 - USED CARS SALES
    // GET API
    public static final String USED_CARS_SALES_GET_SUMMARY = "GET - USED CARS SALES DATA";
    public static final String USED_CARS_SALES_SUCCESS = "USED CARS SALES DATA FETCHED SUCCESSFULLY.";
    public static final String USED_CARS_SALES_NO_DATA_FOUND = "NO DATA FOUND FOR USED CARS SALES.";
    // POST API
    public static final String USED_CARS_SALES_POST_SUMMARY = "POST - ADD USED CARS SALES";
    public static final String USED_CARS_SALES_ADD_SUCCESS = "USED CARS SALES DATA ADDED SUCCESSFULLY.";
    public static final String USED_CARS_SALES_ADD_FAILURE = "FAILURE OCCURRED WHILE ADDING USED CARS SALES DATA.";
    // DELETE API
    public static final String USED_CARS_SALES_DELETE_ALL_SUMMARY = "DELETE ALL - USED CARS SALES DATA";
    public static final String USED_CARS_SALES_DELETE_ALL_SUCCESS = "USED CARS SALES DATA DELETED SUCCESSFULLY.";
    public static final String USED_CARS_SALES_DELETE_ALL_FAILURE = "FAILURE OCCURRED WHILE DELETING USED CARS SALES DATA.";

    // 2 - USED CARS TOP COLORS SALES
    // GET API
    public static final String USED_CARS_TOP_COLORS_SALES_GET_SUMMARY = "GET - USED CARS TOP COLORS SALES DATA";
    public static final String USED_CARS_TOP_COLORS_SALES_SUCCESS = "USED CARS TOP COLORS SALES DATA FETCHED SUCCESSFULLY.";
    public static final String USED_CARS_TOP_COLORS_SALES_NO_DATA_FOUND = "NO DATA FOUND FOR USED CARS TOP COLORS SALES.";
    // POST API
    public static final String USED_CARS_TOP_COLORS_SALES_POST_SUMMARY = "POST - ADD USED CARS TOP COLORS SALES";
    public static final String USED_CARS_TOP_COLORS_SALES_ADD_SUCCESS = "USED CARS TOP COLORS SALES DATA ADDED SUCCESSFULLY.";
    public static final String USED_CARS_TOP_COLORS_SALES_ADD_FAILURE = "FAILURE OCCURRED WHILE ADDING USED CARS TOP COLORS SALES DATA.";
    // DELETE API
    public static final String USED_CARS_TOP_COLORS_SALES_DELETE_ALL_SUMMARY = "DELETE ALL - USED CARS TOP COLORS SALES DATA";
    public static final String USED_CARS_TOP_COLORS_SALES_DELETE_ALL_SUCCESS = "USED CARS TOP COLORS SALES DATA DELETED SUCCESSFULLY.";
    public static final String USED_CARS_TOP_COLORS_SALES_DELETE_ALL_FAILURE = "FAILURE OCCURRED WHILE DELETING USED CARS TOP COLORS SALES DATA.";


    // 3 - USED CARS TOP MODELS SALES
    // GET API
    public static final String USED_CARS_TOP_MODELS_SALES_GET_SUMMARY = "GET - USED CARS TOP MODELS SALES DATA";
    public static final String USED_CARS_TOP_MODELS_SALES_SUCCESS = "USED CARS TOP MODELS SALES DATA FETCHED SUCCESSFULLY.";
    public static final String USED_CARS_TOP_MODELS_SALES_NO_DATA_FOUND = "NO DATA FOUND FOR USED CARS TOP MODELS SALES.";
    // POST API
    public static final String USED_CARS_TOP_MODELS_SALES_POST_SUMMARY = "POST - ADD USED CARS TOP MODELS SALES";
    public static final String USED_CARS_TOP_MODELS_SALES_ADD_SUCCESS = "USED CARS TOP MODELS SALES DATA ADDED SUCCESSFULLY.";
    public static final String USED_CARS_TOP_MODELS_SALES_ADD_FAILURE = "FAILURE OCCURRED WHILE ADDING USED CARS TOP MODELS SALES DATA.";
    // DELETE API
    public static final String USED_CARS_TOP_MODELS_SALES_DELETE_ALL_SUMMARY = "DELETE ALL - USED CARS TOP MODELS SALES DATA";
    public static final String USED_CARS_TOP_MODELS_SALES_DELETE_ALL_SUCCESS = "USED CARS TOP MODELS SALES DATA DELETED SUCCESSFULLY.";
    public static final String USED_CARS_TOP_MODELS_SALES_DELETE_ALL_FAILURE = "FAILURE OCCURRED WHILE DELETING USED CARS TOP MODELS SALES DATA.";

    // 4 - USED CARS TOP REGIONS SALES
    // GET API
    public static final String USED_CARS_TOP_REGIONS_SALES_GET_SUMMARY = "GET - USED CARS TOP REGIONS SALES DATA";
    public static final String USED_CARS_TOP_REGIONS_SALES_SUCCESS = "USED CARS TOP REGIONS SALES DATA FETCHED SUCCESSFULLY.";
    public static final String USED_CARS_TOP_REGIONS_SALES_NO_DATA_FOUND = "NO DATA FOUND FOR USED CARS TOP REGIONS SALES.";
    // POST API
    public static final String USED_CARS_TOP_REGIONS_SALES_POST_SUMMARY = "POST - ADD USED CARS TOP REGIONS SALES";
    public static final String USED_CARS_TOP_REGIONS_SALES_ADD_SUCCESS = "USED CARS TOP REGIONS SALES DATA ADDED SUCCESSFULLY.";
    public static final String USED_CARS_TOP_REGIONS_SALES_ADD_FAILURE = "FAILURE OCCURRED WHILE ADDING USED CARS TOP REGIONS SALES DATA.";
    // DELETE API
    public static final String USED_CARS_TOP_REGIONS_SALES_DELETE_ALL_SUMMARY = "DELETE ALL - USED CARS TOP REGIONS SALES DATA";
    public static final String USED_CARS_TOP_REGIONS_SALES_DELETE_ALL_SUCCESS = "USED CARS TOP REGIONS SALES DATA DELETED SUCCESSFULLY.";
    public static final String USED_CARS_TOP_REGIONS_SALES_DELETE_ALL_FAILURE = "FAILURE OCCURRED WHILE DELETING USED CARS TOP REGIONS SALES DATA.";

}
